[tool.poetry]
name = "my_esphome"
version = "0.1.0"
description = ""
authors = ["Denis"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
esphome = "^2024.11.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
